logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    com.ujjwalmaletha.arbnbbackend: DEBUG

spring:
  profiles:
    active: dev
  application:
    name: arbnbbackend
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/airbnb_clone}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ujjwal}

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: Hikari
      auto-commit: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
    default-schema: airbnb_clone
    enabled: false
  #    drop-first: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
server:
  port: 8080

okta:
  oauth2:
    issuer: ${ISSUER:https://dev-6f3vy7sf26wpcync.us.auth0.com/}
    client-id: ${AUTH0_CLIENT_ID:LOfTPaIU9aRzB3CVCOiM8semOWwssW2I}
    client-secret: ${AUTH0_CLIENT_SECRET:k2QmjaJ9LPpxS8pWWH3tp70qWc4mbOD2uas0Z_mxYFi6CSDgwugfjFqPq1UO6KM2}

application:
  auth0:
    role-landlord-id: ${LANDLORD_ID:rol_HTo2RjZ517X52Li0}